export const FETCH_ONE_MEMBER_REQUEST = "FETCH_ONE_MEMBER_REQUEST";
export const FETCH_ONE_MEMBER_SUCCESS = "FETCH_ONE_MEMBER_SUCCESS";
export const FETCH_ONE_MEMBER_FAILURE = "FETCH_ONE_MEMBER_FAILURE";
